import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useSelector,useDispatch} from 'react-redux';
import increment from '../actions/increment';
import decrement from '../actions/decrement';
import authAction from '../actions/auth';

export default function Home() {
  const counter = useSelector((state)=> state.counter);
  const auth = useSelector((state) => state.auth);

  const dispatch = useDispatch();

  return (
      <>
          <nav>
              <ul>
                  {
                      auth &&
                      <>
                          <li>Home</li>
                          <li>About</li>
                          <li onClick={()=>dispatch(authAction.logout())}>Logout</li>
                      </>
                  }
                  {
                      !auth && <li onClick={()=>dispatch(authAction.login())}>Login</li>
                  }
              </ul>
          </nav>
          <div className={styles.container}>
              <Head>
                  <title>Create Next App</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
              </Head>
              <div>
                  counter : {counter}
                  <div>
                      <button onClick={()=>dispatch(increment())}>+</button>
                      <button onClick={()=>dispatch(decrement())}>-</button>
                  </div>
              </div>

          </div>
      </>

  )
}
